### ISSUE TITLE
SnippetContactReportCCD

### ISSUE THREAD

**Issue by wangdahao** [NVIDIAGameWorks/PhysX#348] opened 2020-10-10 03:15 UTC
After running my “SnippetContactReportCCD” snippet, the ball is still, I don't know how to make it move！

**Comment by Pierre-Terdiman** [comment] 2020-10-28 15:03
I didn't write that snippet but I'm pretty sure it's by design. It captures & shows what happens in a single frame using CCD, displaying the CCD contacts, etc.

**Comment by PierreTerdiman** [comment] 2021-04-09 13:50
Closing for now, please re-open if you still think there is a problem.

**Closed as completed by PierreTerdiman** 2021-04-09 13:50 UTC
